const DummySidebar = {
  id: 2,
  parent_id: 1,
  name: 'Default',
  is_active: true,
  position: 1,
  level: 1,
  product_count: 1280,
  children_data: [
    {
      id: 41,
      parent_id: 2,
      name: 'Kategori Produk',
      is_active: true,
      position: 1,
      level: 2,
      product_count: 1275,
      children_data: [
        {
          id: 113,
          parent_id: 41,
          name: 'Food & Beverages',
          is_active: true,
          position: 2,
          level: 3,
          product_count: 859,
          children_data: [
            {
              id: 43,
              parent_id: 113,
              name: 'Minuman',
              is_active: true,
              position: 1,
              level: 4,
              product_count: 162,
              children_data: [
                {
                  id: 54,
                  parent_id: 43,
                  name: 'Superdrink',
                  is_active: true,
                  position: 1,
                  level: 5,
                  product_count: 55,
                  children_data: [],
                },
                {
                  id: 56,
                  parent_id: 43,
                  name: 'Tea & Coffee',
                  is_active: true,
                  position: 2,
                  level: 5,
                  product_count: 36,
                  children_data: [],
                },
                {
                  id: 69,
                  parent_id: 43,
                  name: 'Traditional Drink',
                  is_active: true,
                  position: 3,
                  level: 5,
                  product_count: 48,
                  children_data: [],
                },
                {
                  id: 75,
                  parent_id: 43,
                  name: 'Processed Drink',
                  is_active: true,
                  position: 4,
                  level: 5,
                  product_count: 17,
                  children_data: [],
                },
                {
                  id: 72,
                  parent_id: 43,
                  name: 'Honey',
                  is_active: false,
                  position: 5,
                  level: 5,
                  product_count: 5,
                  children_data: [],
                },
                {
                  id: 55,
                  parent_id: 43,
                  name: 'Plant Based Milk',
                  is_active: false,
                  position: 6,
                  level: 5,
                  product_count: 0,
                  children_data: [],
                },
                {
                  id: 57,
                  parent_id: 43,
                  name: 'Dairy',
                  is_active: false,
                  position: 7,
                  level: 5,
                  product_count: 0,
                  children_data: [],
                },
                {
                  id: 135,
                  parent_id: 43,
                  name: 'Nectar & Juice',
                  is_active: true,
                  position: 8,
                  level: 5,
                  product_count: 0,
                  children_data: [],
                },
              ],
            },
            {
              id: 42,
              parent_id: 113,
              name: 'Snacks',
              is_active: true,
              position: 2,
              level: 4,
              product_count: 307,
              children_data: [
                {
                  id: 48,
                  parent_id: 42,
                  name: 'Cookies',
                  is_active: true,
                  position: 1,
                  level: 5,
                  product_count: 50,
                  children_data: [],
                },
                {
                  id: 126,
                  parent_id: 42,
                  name: 'Biscuits & Crackers',
                  is_active: true,
                  position: 2,
                  level: 5,
                  product_count: 17,
                  children_data: [],
                },
                {
                  id: 47,
                  parent_id: 42,
                  name: 'Protein & Snack Bars',
                  is_active: true,
                  position: 3,
                  level: 5,
                  product_count: 11,
                  children_data: [],
                },
                {
                  id: 71,
                  parent_id: 42,
                  name: 'Cereal & Granola',
                  is_active: false,
                  position: 4,
                  level: 5,
                  product_count: 4,
                  children_data: [],
                },
                {
                  id: 49,
                  parent_id: 42,
                  name: 'Nuts',
                  is_active: true,
                  position: 5,
                  level: 5,
                  product_count: 34,
                  children_data: [],
                },
                {
                  id: 50,
                  parent_id: 42,
                  name: 'Chips',
                  is_active: true,
                  position: 6,
                  level: 5,
                  product_count: 52,
                  children_data: [],
                },
                {
                  id: 51,
                  parent_id: 42,
                  name: 'Candy & Chocolate',
                  is_active: true,
                  position: 7,
                  level: 5,
                  product_count: 109,
                  children_data: [],
                },
                {
                  id: 52,
                  parent_id: 42,
                  name: 'Dried Fruits',
                  is_active: true,
                  position: 8,
                  level: 5,
                  product_count: 26,
                  children_data: [],
                },
                {
                  id: 128,
                  parent_id: 42,
                  name: 'Bundle Snacks',
                  is_active: true,
                  position: 10,
                  level: 5,
                  product_count: 3,
                  children_data: [],
                },
              ],
            },
            {
              id: 44,
              parent_id: 113,
              name: 'Pasta & Biji-bijian',
              is_active: true,
              position: 3,
              level: 4,
              product_count: 158,
              children_data: [
                {
                  id: 58,
                  parent_id: 44,
                  name: 'Pasta Kering',
                  is_active: true,
                  position: 1,
                  level: 5,
                  product_count: 40,
                  children_data: [],
                },
                {
                  id: 134,
                  parent_id: 44,
                  name: 'Mie Kering',
                  is_active: true,
                  position: 2,
                  level: 5,
                  product_count: 26,
                  children_data: [],
                },
                {
                  id: 59,
                  parent_id: 44,
                  name: 'Sereal',
                  is_active: true,
                  position: 3,
                  level: 5,
                  product_count: 52,
                  children_data: [],
                },
                {
                  id: 60,
                  parent_id: 44,
                  name: 'Grains & Seeds',
                  is_active: true,
                  position: 4,
                  level: 5,
                  product_count: 42,
                  children_data: [],
                },
              ],
            },
            {
              id: 45,
              parent_id: 113,
              name: 'Dapur',
              is_active: true,
              position: 4,
              level: 4,
              product_count: 231,
              children_data: [
                {
                  id: 63,
                  parent_id: 45,
                  name: 'Herbs, Spices & Seasonings',
                  is_active: true,
                  position: 1,
                  level: 5,
                  product_count: 107,
                  children_data: [],
                },
                {
                  id: 73,
                  parent_id: 45,
                  name: 'Honey & Sweeteners',
                  is_active: true,
                  position: 2,
                  level: 5,
                  product_count: 37,
                  children_data: [],
                },
                {
                  id: 64,
                  parent_id: 45,
                  name: 'Spreads',
                  is_active: true,
                  position: 3,
                  level: 5,
                  product_count: 18,
                  children_data: [],
                },
                {
                  id: 74,
                  parent_id: 45,
                  name: 'Baking',
                  is_active: true,
                  position: 4,
                  level: 5,
                  product_count: 23,
                  children_data: [],
                },
                {
                  id: 61,
                  parent_id: 45,
                  name: 'Oils & Vinegars',
                  is_active: true,
                  position: 5,
                  level: 5,
                  product_count: 16,
                  children_data: [],
                },
                {
                  id: 62,
                  parent_id: 45,
                  name: 'Frozen Foods',
                  is_active: false,
                  position: 7,
                  level: 5,
                  product_count: 0,
                  children_data: [],
                },
                {
                  id: 130,
                  parent_id: 45,
                  name: 'Condiments & Sauces',
                  is_active: true,
                  position: 9,
                  level: 5,
                  product_count: 27,
                  children_data: [],
                },
                {
                  id: 133,
                  parent_id: 45,
                  name: 'Dry Beans & Peas',
                  is_active: true,
                  position: 10,
                  level: 5,
                  product_count: 0,
                  children_data: [],
                },
                {
                  id: 132,
                  parent_id: 45,
                  name: 'Packaged Foods',
                  is_active: true,
                  position: 11,
                  level: 5,
                  product_count: 0,
                  children_data: [],
                },
              ],
            },
            {
              id: 131,
              parent_id: 113,
              name: 'Bundle Food & Beverages',
              is_active: true,
              position: 5,
              level: 4,
              product_count: 10,
              children_data: [],
            },
            {
              id: 144,
              parent_id: 113,
              name: 'Baby & Kids Meal',
              is_active: true,
              position: 6,
              level: 4,
              product_count: 7,
              children_data: [],
            },
          ],
        },
        {
          id: 114,
          parent_id: 41,
          name: 'Health & Wellness',
          is_active: true,
          position: 3,
          level: 3,
          product_count: 339,
          children_data: [
            {
              id: 76,
              parent_id: 114,
              name: 'Body Care',
              is_active: true,
              position: 1,
              level: 4,
              product_count: 55,
              children_data: [
                {
                  id: 77,
                  parent_id: 76,
                  name: 'Body Wash',
                  is_active: true,
                  position: 1,
                  level: 5,
                  product_count: 23,
                  children_data: [],
                },
                {
                  id: 78,
                  parent_id: 76,
                  name: 'Bath Salt',
                  is_active: true,
                  position: 2,
                  level: 5,
                  product_count: 0,
                  children_data: [],
                },
                {
                  id: 79,
                  parent_id: 76,
                  name: 'Body Lotion',
                  is_active: true,
                  position: 3,
                  level: 5,
                  product_count: 22,
                  children_data: [],
                },
                {
                  id: 80,
                  parent_id: 76,
                  name: 'Body Scrub',
                  is_active: true,
                  position: 4,
                  level: 5,
                  product_count: 5,
                  children_data: [],
                },
                {
                  id: 81,
                  parent_id: 76,
                  name: 'Body Oil',
                  is_active: true,
                  position: 5,
                  level: 5,
                  product_count: 9,
                  children_data: [],
                },
              ],
            },
            {
              id: 82,
              parent_id: 114,
              name: 'Facial Care',
              is_active: true,
              position: 2,
              level: 4,
              product_count: 29,
              children_data: [
                {
                  id: 83,
                  parent_id: 82,
                  name: 'Face Wash',
                  is_active: true,
                  position: 1,
                  level: 5,
                  product_count: 8,
                  children_data: [],
                },
                {
                  id: 84,
                  parent_id: 82,
                  name: 'Oil & Moisturizer',
                  is_active: true,
                  position: 2,
                  level: 5,
                  product_count: 7,
                  children_data: [],
                },
                {
                  id: 85,
                  parent_id: 82,
                  name: 'Toner',
                  is_active: true,
                  position: 3,
                  level: 5,
                  product_count: 2,
                  children_data: [],
                },
                {
                  id: 86,
                  parent_id: 82,
                  name: 'Face Mask',
                  is_active: true,
                  position: 4,
                  level: 5,
                  product_count: 0,
                  children_data: [],
                },
                {
                  id: 87,
                  parent_id: 82,
                  name: 'Serum',
                  is_active: true,
                  position: 5,
                  level: 5,
                  product_count: 13,
                  children_data: [],
                },
              ],
            },
            {
              id: 88,
              parent_id: 114,
              name: 'Hair Care',
              is_active: true,
              position: 3,
              level: 4,
              product_count: 34,
              children_data: [
                {
                  id: 89,
                  parent_id: 88,
                  name: 'Shampoo & Conditioner',
                  is_active: true,
                  position: 1,
                  level: 5,
                  product_count: 25,
                  children_data: [],
                },
                {
                  id: 90,
                  parent_id: 88,
                  name: 'Hair Mask',
                  is_active: true,
                  position: 2,
                  level: 5,
                  product_count: 1,
                  children_data: [],
                },
                {
                  id: 91,
                  parent_id: 88,
                  name: 'Hair Oil & Serum',
                  is_active: true,
                  position: 3,
                  level: 5,
                  product_count: 9,
                  children_data: [],
                },
              ],
            },
            {
              id: 92,
              parent_id: 114,
              name: 'Aromatherapy',
              is_active: true,
              position: 4,
              level: 4,
              product_count: 0,
              children_data: [
                {
                  id: 93,
                  parent_id: 92,
                  name: 'Essential Oil',
                  is_active: true,
                  position: 1,
                  level: 5,
                  product_count: 0,
                  children_data: [],
                },
                {
                  id: 94,
                  parent_id: 92,
                  name: 'Scented Candle',
                  is_active: true,
                  position: 2,
                  level: 5,
                  product_count: 0,
                  children_data: [],
                },
                {
                  id: 95,
                  parent_id: 92,
                  name: 'Reed Diffuser',
                  is_active: true,
                  position: 3,
                  level: 5,
                  product_count: 0,
                  children_data: [],
                },
              ],
            },
            {
              id: 96,
              parent_id: 114,
              name: 'Mens Grooming',
              is_active: true,
              position: 5,
              level: 4,
              product_count: 0,
              children_data: [
                {
                  id: 97,
                  parent_id: 96,
                  name: 'Mens Shaving Kit',
                  is_active: true,
                  position: 1,
                  level: 5,
                  product_count: 0,
                  children_data: [],
                },
                {
                  id: 98,
                  parent_id: 96,
                  name: 'Serum',
                  is_active: true,
                  position: 2,
                  level: 5,
                  product_count: 0,
                  children_data: [],
                },
              ],
            },
            {
              id: 99,
              parent_id: 114,
              name: 'Personal Care',
              is_active: true,
              position: 6,
              level: 4,
              product_count: 143,
              children_data: [
                {
                  id: 100,
                  parent_id: 99,
                  name: 'Hand Wash',
                  is_active: true,
                  position: 1,
                  level: 5,
                  product_count: 9,
                  children_data: [],
                },
                {
                  id: 101,
                  parent_id: 99,
                  name: 'Sanitizer',
                  is_active: true,
                  position: 2,
                  level: 5,
                  product_count: 130,
                  children_data: [],
                },
                {
                  id: 102,
                  parent_id: 99,
                  name: 'Body Mist',
                  is_active: true,
                  position: 3,
                  level: 5,
                  product_count: 0,
                  children_data: [],
                },
                {
                  id: 103,
                  parent_id: 99,
                  name: 'Body Spray',
                  is_active: true,
                  position: 4,
                  level: 5,
                  product_count: 0,
                  children_data: [],
                },
                {
                  id: 115,
                  parent_id: 99,
                  name: 'Feminine Care',
                  is_active: true,
                  position: 5,
                  level: 5,
                  product_count: 4,
                  children_data: [],
                },
                {
                  id: 138,
                  parent_id: 99,
                  name: 'Deodorant',
                  is_active: true,
                  position: 6,
                  level: 5,
                  product_count: 1,
                  children_data: [],
                },
              ],
            },
            {
              id: 104,
              parent_id: 114,
              name: 'Laundry',
              is_active: true,
              position: 7,
              level: 4,
              product_count: 12,
              children_data: [
                {
                  id: 105,
                  parent_id: 104,
                  name: 'Fabric Spray',
                  is_active: true,
                  position: 1,
                  level: 5,
                  product_count: 7,
                  children_data: [],
                },
                {
                  id: 106,
                  parent_id: 104,
                  name: 'Detergent',
                  is_active: true,
                  position: 2,
                  level: 5,
                  product_count: 6,
                  children_data: [],
                },
              ],
            },
            {
              id: 107,
              parent_id: 114,
              name: 'House Keeping',
              is_active: true,
              position: 8,
              level: 4,
              product_count: 17,
              children_data: [
                {
                  id: 108,
                  parent_id: 107,
                  name: 'Dish Soap',
                  is_active: true,
                  position: 1,
                  level: 5,
                  product_count: 11,
                  children_data: [],
                },
                {
                  id: 109,
                  parent_id: 107,
                  name: 'Floor Cleaner',
                  is_active: true,
                  position: 2,
                  level: 5,
                  product_count: 6,
                  children_data: [],
                },
              ],
            },
            {
              id: 110,
              parent_id: 114,
              name: 'General',
              is_active: true,
              position: 9,
              level: 4,
              product_count: 17,
              children_data: [
                {
                  id: 111,
                  parent_id: 110,
                  name: 'Multi-purpose Spray',
                  is_active: true,
                  position: 1,
                  level: 5,
                  product_count: 12,
                  children_data: [],
                },
                {
                  id: 112,
                  parent_id: 110,
                  name: 'Air Freshener',
                  is_active: true,
                  position: 2,
                  level: 5,
                  product_count: 4,
                  children_data: [],
                },
                {
                  id: 137,
                  parent_id: 110,
                  name: 'Fruits & Veggie Wash',
                  is_active: true,
                  position: 3,
                  level: 5,
                  product_count: 1,
                  children_data: [],
                },
              ],
            },
            {
              id: 116,
              parent_id: 114,
              name: 'Vitamins & Supplements',
              is_active: true,
              position: 10,
              level: 4,
              product_count: 56,
              children_data: [],
            },
            {
              id: 145,
              parent_id: 114,
              name: 'Mother Care & Health',
              is_active: true,
              position: 11,
              level: 4,
              product_count: 9,
              children_data: [],
            },
            {
              id: 146,
              parent_id: 114,
              name: 'Baby Health & Care',
              is_active: true,
              position: 12,
              level: 4,
              product_count: 20,
              children_data: [],
            },
          ],
        },
      ],
    },
    {
      id: 66,
      parent_id: 2,
      name: 'Exclusive Awal Mula',
      is_active: true,
      position: 2,
      level: 2,
      product_count: 110,
      children_data: [],
    },
    {
      id: 139,
      parent_id: 2,
      name: 'Lifestyle',
      is_active: true,
      position: 3,
      level: 2,
      product_count: 259,
      children_data: [
        {
          id: 150,
          parent_id: 139,
          name: 'Diet',
          is_active: true,
          position: 1,
          level: 3,
          product_count: 187,
          children_data: [
            {
              id: 140,
              parent_id: 150,
              name: 'Vegan',
              is_active: true,
              position: 1,
              level: 4,
              product_count: 94,
              children_data: [],
            },
            {
              id: 141,
              parent_id: 150,
              name: 'Gluten Free',
              is_active: true,
              position: 2,
              level: 4,
              product_count: 72,
              children_data: [],
            },
            {
              id: 147,
              parent_id: 150,
              name: 'Low Sugar',
              is_active: true,
              position: 3,
              level: 4,
              product_count: 59,
              children_data: [],
            },
          ],
        },
        {
          id: 151,
          parent_id: 139,
          name: 'Nutrient Claims',
          is_active: true,
          position: 2,
          level: 3,
          product_count: 156,
          children_data: [
            {
              id: 142,
              parent_id: 151,
              name: 'Low Calorie',
              is_active: true,
              position: 1,
              level: 4,
              product_count: 41,
              children_data: [],
            },
            {
              id: 148,
              parent_id: 151,
              name: 'Dairy Free',
              is_active: true,
              position: 2,
              level: 4,
              product_count: 51,
              children_data: [],
            },
            {
              id: 143,
              parent_id: 151,
              name: 'High in Protein',
              is_active: true,
              position: 3,
              level: 4,
              product_count: 62,
              children_data: [],
            },
            {
              id: 149,
              parent_id: 151,
              name: 'High Fiber',
              is_active: true,
              position: 4,
              level: 4,
              product_count: 45,
              children_data: [],
            },
          ],
        },
      ],
    },
    {
      id: 129,
      parent_id: 2,
      name: 'Goods & Gifts',
      is_active: true,
      position: 4,
      level: 2,
      product_count: 15,
      children_data: [],
    },
    {
      id: 67,
      parent_id: 2,
      name: 'Promo',
      is_active: true,
      position: 6,
      level: 2,
      product_count: 56,
      children_data: [
        {
          id: 124,
          parent_id: 67,
          name: 'Promo Yagi',
          is_active: true,
          position: 1,
          level: 3,
          product_count: 2,
          children_data: [],
        },
        {
          id: 125,
          parent_id: 67,
          name: 'Promo BeautyBarn',
          is_active: true,
          position: 2,
          level: 3,
          product_count: 2,
          children_data: [],
        },
        {
          id: 127,
          parent_id: 67,
          name: 'Promo pouch',
          is_active: true,
          position: 3,
          level: 3,
          product_count: 2,
          children_data: [],
        },
      ],
    },
    {
      id: 46,
      parent_id: 2,
      name: 'Semua Produk',
      is_active: true,
      position: 7,
      level: 2,
      product_count: 1250,
      children_data: [],
    },
    {
      id: 68,
      parent_id: 2,
      name: 'Mula Akselerator',
      is_active: true,
      position: 8,
      level: 2,
      product_count: 13,
      children_data: [],
    },
    {
      id: 118,
      parent_id: 2,
      name: 'Exclusive H&W',
      is_active: true,
      position: 9,
      level: 2,
      product_count: 11,
      children_data: [],
    },
    {
      id: 119,
      parent_id: 2,
      name: 'Exclusive F&B',
      is_active: true,
      position: 10,
      level: 2,
      product_count: 16,
      children_data: [],
    },
    {
      id: 120,
      parent_id: 2,
      name: 'Promo F&B',
      is_active: true,
      position: 11,
      level: 2,
      product_count: 4,
      children_data: [],
    },
    {
      id: 121,
      parent_id: 2,
      name: 'Promo H&W',
      is_active: true,
      position: 12,
      level: 2,
      product_count: 11,
      children_data: [],
    },
    {
      id: 122,
      parent_id: 2,
      name: 'Rekomendaasi H&W',
      is_active: true,
      position: 13,
      level: 2,
      product_count: 11,
      children_data: [],
    },
    {
      id: 123,
      parent_id: 2,
      name: 'Rekomendaasi F&B',
      is_active: true,
      position: 14,
      level: 2,
      product_count: 9,
      children_data: [],
    },
    {
      id: 136,
      parent_id: 2,
      name: 'Suggest Product',
      is_active: true,
      position: 15,
      level: 2,
      product_count: 5,
      children_data: [],
    },
  ],
}
export default DummySidebar